### ISSUE TITLE
Would like to talk about DCI

### ISSUE THREAD

**Issue by Nhiokh** [ciscoheat/eslint-plugin-dci-lint#1]
Hi there! I've been trying to reach you for a moment now. I have tried to implement my own version of a TicTacToe game in DCI and I would love some feedback on the matter if you could spare me some time?

**Comment by ciscoheat** [comment]
Hello, sure, I'm happy to give you some feedback! Either here, or if you want to chat in realtime you can find me on discord (ciscoheat), on the Superforms discord, send me a PM there: https://discord.gg/BZQQTDBh
